#!/bin/bash
NAME="my_Project"

# Django project directory & communicte using this unix socket
DJANGODIR=/home/tssdev/scrapper_tool/TSS-Backend
SOCKFILE=/home/tssdev/scrapper_tool/gunicorn.sock

# The user & group to run as
USER=tssdev
GROUP=tssdev

# No. of worker processes should Gunicorn spawn
NUM_WORKERS=5
NUM_CLASS=gevent
NUM_WORK_CONN=2000
NUM_THREADS=4

PYTHONPATH=/home/tssdev/scrapper_tool/tss-venv

# Which settings file should Django use
DJANGO_SETTINGS_MODULE=scraper_project.settings

# WSGI module name
DJANGO_WSGI_MODULE=scraper_project.wsgi

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source ../tss-venv/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH




# Start your Django Gunicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)

exec ../tss-venv/bin/gunicorn  --workers $NUM_WORKERS --user=$USER --group=$GROUP  --bind=unix:$SOCKFILE --log-level=debug --log-file=/var/log/gunicorn.log --worker-class $NUM_CLASS --threads $NUM_THREADS --worker-connections $NUM_WORK_CONN --max-requests=2000 --max-requests-jitter=30 --timeout=21600 $DJANGO_WSGI_MODULE:application

